apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.12.12_15.14-6d2623ef615d
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  ingresses:
    - https://aktivitetsplan.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-dev
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.dev.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-dev"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true },
            { "fromPath": "/veilarblest", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true },
            { "fromPath": "/veilarbdialog", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true },
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true }
          ],
          "redirects": [
              {
                "fromPath": "/api/auth",
                "toUrl": "/auth/info"
              },
              {
                "fromPath": "/aktivitetsplan",
                "toUrl": "{{AKTIVITETSPLAN_URL}}"
              },              {
                "fromPath": "/arbeidssokerregistrering",
                "toUrl": "{{ARBEIDSSOKERREGISTRERING_URL}}"
              },              {
                "fromPath": "/minside",
                "toUrl": "{{MINSIDE_URL}}"
              },              {
                "fromPath": "/veientilarbeid",
                "toUrl": "{{VEIENTILARBEID_URL}}"
              },              {
                "fromPath": "/arbeidsrettet-dialog",
                "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
                "preserveFromPath": "true"
              },
              {
                "fromPath": "/dialog",
                "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
                "preserveFromPath": "true"
              }
          ]
        }
