apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.09.09_12.03-17f7a5dfa7e4
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://aktivitetsplan.dev.intern.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-dev-intern
  envFrom:
    - configmap: pto-config
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-dev-intern"
          },
          "cors": {
            "origin": ["https://veilarbpersonflate.dev.intern.nav.no", "https://veilarbpersonflate.intern.nav.no"],
            "credentials": true,
            "maxAge": 7200
          },
          "header": {
            "csp": {
              "frameSrc": ["vars.hotjar.com", "video.qbrick.com"]
            }
          }
        }
